server:
  port: 8001

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2024?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: db2024
    password: 123456

mybatis:
#  指定MyBatis的Mapper XML文件的位置,表示在项目的classpath路径下的mapper目录中，所有以.xml结尾的文件都会被加载为Mapper文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: yang.example.entities
  configuration:
    # 开启自动驼峰命名转换
    map-underscore-to-camel-case: true